grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 2
  
model_selection:
  module_2:
    class: DecisionTreeClassifier
    module: sklearn.tree
    params:
      max_depth: 2
    search_param_grid:
      max_depth:
      - 2
      - 3
      - 4
      - 5
      - 6
      - 8
      - 10
      - 12
      - 15
      - 20

  