columns:
  elevation: int64
  aspect: int64
  slope: int64
  horizontal_distance_to_hydrology: int64
  Vertical_Distance_To_Hydrology: int64
  Horizontal_Distance_To_Roadways: int64
  Horizontal_Distance_To_Fire_Points: int64
  wilderness_area1: int64
  wilderness_area2: int64
  wilderness_area3: int64
  wilderness_area4: int64
  soil_type_1: int64
  soil_type_2: int64
  soil_type_3: int64
  soil_type_4: int64
  soil_type_5: int64
  soil_type_6: int64
  soil_type_7: int64
  soil_type_8: int64
  soil_type_9: int64
  soil_type_10: int64
  soil_type_11: int64
  soil_type_12: int64
  soil_type_13: int64
  soil_type_14: int64
  soil_type_15: int64
  soil_type_16: int64
  soil_type_17: int64
  soil_type_18: int64
  soil_type_19: int64
  soil_type_20: int64
  soil_type_21: int64
  soil_type_22: int64
  soil_type_23: int64
  soil_type_24: int64
  soil_type_25: int64
  soil_type_26: int64
  soil_type_27: int64
  soil_type_28: int64
  soil_type_29: int64
  soil_type_30: int64
  soil_type_31: int64
  soil_type_32: int64
  soil_type_33: int64
  soil_type_34: int64
  soil_type_35: int64
  soil_type_36: int64
  soil_type_37: int64
  soil_type_38: int64
  soil_type_39: int64
  soil_type_40: int64
  class: int64

numerical_columns:
  - elevation
  - aspect
  - slope
  - horizontal_distance_to_hydrology
  - Vertical_Distance_To_Hydrology
  - Horizontal_Distance_To_Roadways
  - Horizontal_Distance_To_Fire_Points
  - wilderness_area1
  - wilderness_area2
  - wilderness_area3
  - wilderness_area4
  - soil_type_1
  - soil_type_2
  - soil_type_3
  - soil_type_4
  - soil_type_5
  - soil_type_6
  - soil_type_7
  - soil_type_8
  - soil_type_9
  - soil_type_10
  - soil_type_11
  - soil_type_12
  - soil_type_13
  - soil_type_14
  - soil_type_15
  - soil_type_16
  - soil_type_17
  - soil_type_18
  - soil_type_19
  - soil_type_20
  - soil_type_21
  - soil_type_22
  - soil_type_23
  - soil_type_24
  - soil_type_25
  - soil_type_26
  - soil_type_27
  - soil_type_28
  - soil_type_29
  - soil_type_30
  - soil_type_31
  - soil_type_32
  - soil_type_33
  - soil_type_34
  - soil_type_35
  - soil_type_36
  - soil_type_37
  - soil_type_38
  - soil_type_39
  - soil_type_40

categorical_columns:
  - class

target_column:
  - class